# Generated by Django 5.2.5 on 2025-09-02 10:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(help_text='Child must be born after January 1, 2010')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('child_class', models.CharField(choices=[('creche', 'Creche - 0-2yrs old'), ('little_tackers', 'Little Tackers - 3yrs-Kindy (2026)'), ('minis', 'Minis - School Years 1-2 (2026)')], max_length=20)),
                ('has_dietary_needs', models.BooleanField(default=False)),
                ('dietary_needs_detail', models.TextField(blank=True)),
                ('has_medical_needs', models.BooleanField(default=False)),
                ('medical_allergy_details', models.TextField(blank=True)),
                ('photo_consent', models.BooleanField(default=False)),
                ('qr_code_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qr_code_image', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('checked_in_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_children', to=settings.AUTH_USER_MODEL)),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_out_children', to=settings.AUTH_USER_MODEL)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='registration.child')),
            ],
            options={
                'ordering': ['-date', '-time_in'],
            },
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Postcode must be 4 digits')])),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', 'Phone number must be up to 10 digits')])),
                ('how_heard_about', models.CharField(choices=[('friend', 'My Friend Recommended (please tell us who in additional information)'), ('church', 'At Lighthouse Church'), ('kids_club', "Lighthouse Kids' Club")], max_length=20)),
                ('additional_information', models.TextField(blank=True)),
                ('attends_church_regularly', models.BooleanField()),
                ('which_church', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_name', models.CharField(max_length=200)),
                ('emergency_contact_phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', 'Phone number must be up to 10 digits')])),
                ('emergency_contact_relationship', models.CharField(choices=[('other_parent', 'Other Parent'), ('grandparent', 'Grandparent'), ('uncle_aunty', 'Uncle/Aunty')], max_length=20)),
                ('first_aid_consent', models.BooleanField(default=False)),
                ('injury_waiver', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='registration.parentprofile'),
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_classes', models.CharField(choices=[('creche', 'Creche - 0-2yrs old'), ('little_tackers', 'Little Tackers - 3yrs-Kindy (2026)'), ('minis', 'Minis - School Years 1-2 (2026)')], help_text='Classes this teacher is responsible for', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
