# Generated by Django 5.2.5 on 2025-09-07 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_child_child_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='assigned_classes',
        ),
        migrations.CreateModel(
            name='TeacherClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(choices=[('creche', 'Creche - 0-2yrs old'), ('tackers', 'Little Tackers - 3yrs-Kindy (2026)'), ('minis', 'Minis - School Years 1-2 (2026)'), ('nitro', 'Nitro - School Years 3-4 (2026)'), ('56ers', '56ers - School Years 5-6 (2026)')], max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Is this teacher the primary teacher for this class?')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='registration.teacherprofile')),
            ],
            options={
                'unique_together': {('teacher', 'class_code')},
            },
        ),
    ]
