# Generated by Django 5.2.5 on 2025-09-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_teacherprofile_assigned_classes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('not_arrived', 'Not yet arrived'), ('checked_in', 'Checked in'), ('in_class', 'In class'), ('picked_up', 'Picked up')], default='checked_in', max_length=20),
        ),
    ]
