# Generated by Django 5.2.5 on 2025-09-08 21:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_add_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='parent_qr_code_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='parent_qr_code_image',
            field=models.ImageField(blank=True, upload_to='parent_qr_codes/'),
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('daily_child', 'Daily Child Pass ($6)'), ('daily_family', 'Daily Family Pass ($12)'), ('weekly_child', 'Weekly Child Pass ($20)'), ('weekly_family', 'Weekly Family Pass ($40)')], max_length=20)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('stripe_payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('stripe_session_id', models.CharField(blank=True, max_length=200, null=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='registration.parentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
