# Generated by Django 5.2.5 on 2025-09-09 08:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_add_pass_system_and_parent_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='charge_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='attendance',
            name='charge_reason',
            field=models.TextField(blank=True, help_text='Explanation of charge calculation'),
        ),
    ]
