# Generated by Django 5.2.5 on 2025-09-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_attendance_charge_amount_attendance_charge_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
    ]
