# Generated by Django 5.2.5 on 2025-09-14 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_alter_attendance_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='photo_consent',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='WelcomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParentInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_method', models.CharField(choices=[('parent_search', 'Found by Parent Name'), ('child_search', 'Found by Child Name'), ('no_record', 'No Record Found - Manual Entry')], max_length=20)),
                ('manual_first_name', models.CharField(blank=True, help_text='First name if no record found', max_length=100)),
                ('manual_last_name', models.CharField(blank=True, help_text='Last name if no record found', max_length=100)),
                ('manual_phone', models.CharField(blank=True, help_text='Phone number if no record found', max_length=20)),
                ('manual_email', models.EmailField(blank=True, help_text='Email if no record found', max_length=254)),
                ('manual_address', models.TextField(blank=True, help_text='Address if no record found')),
                ('manual_children_info', models.TextField(blank=True, help_text='Children and class info if no record found')),
                ('interaction_day', models.CharField(choices=[('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20)),
                ('current_church', models.CharField(blank=True, help_text='Which church do they currently attend?', max_length=200)),
                ('attends_church', models.BooleanField(blank=True, help_text='Do they currently attend a church?', null=True)),
                ('faith_status', models.TextField(blank=True, help_text='Current faith status (open-ended)')),
                ('knows_lighthouse_members', models.TextField(blank=True, help_text='Do they know anyone from Lighthouse Church?')),
                ('previous_lighthouse_interaction', models.TextField(blank=True, help_text='Have they interacted with Lighthouse Church before?')),
                ('interested_in_future_events', models.TextField(blank=True, help_text='Interest in future events, services, activities')),
                ('additional_notes', models.TextField(blank=True, help_text='Any additional observations or notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='registration.parentprofile')),
                ('welcomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='registration.welcomerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
