# Generated by Django 5.2.5 on 2025-09-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0007_alter_attendance_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="photo_consent",
            field=models.BooleanField(default=True),
        ),
    ]
