# Generated by Django 5.1.3 on 2025-09-14 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0008_alter_child_photo_consent"),
        ("registration", "0008_alter_child_photo_consent_welcomerprofile_and_more"),
    ]

    operations = []
