# Generated by Django 5.2.5 on 2025-09-14 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_alter_child_photo_consent_welcomerprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentinteraction',
            name='conversation_team_member',
            field=models.CharField(blank=True, help_text='Name of team member who had the conversation (if different from person recording it)', max_length=100),
        ),
        migrations.AlterField(
            model_name='parentinteraction',
            name='welcomer',
            field=models.ForeignKey(help_text='The welcomer who is recording this conversation', on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='registration.welcomerprofile'),
        ),
    ]
