# Generated by Django 5.1.3 on 2025-09-14 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0009_add_conversation_team_member"),
        ("registration", "0009_merge_20250914_0844"),
    ]

    operations = []
