# Generated by Django 5.2.5 on 2025-09-27 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_merge_20250914_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_width', models.IntegerField(default=50, help_text='Label width in millimeters')),
                ('label_height', models.IntegerField(default=38, help_text='Label height in millimeters')),
                ('font_scale', models.FloatField(default=1.0, help_text='Font scale multiplier')),
                ('auto_print_on_checkin', models.BooleanField(default=False, help_text='Automatically print labels when children are checked in')),
                ('printer_name', models.CharField(blank=True, help_text='Name of the printer for automatic printing', max_length=200)),
                ('show_medical_icon', models.BooleanField(default=True, help_text='Show medical needs icon')),
                ('show_dietary_icon', models.BooleanField(default=True, help_text='Show dietary needs icon')),
                ('show_photo_icon', models.BooleanField(default=True, help_text='Show photo consent icon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Label Settings',
                'verbose_name_plural': 'Label Settings',
            },
        ),
    ]
